fail_fast: false
repos:
-   repo: https://github.com/ViRu-ThE-ViRuS/pre-commit-script-runner
    rev: v1.0.0
    hooks:
    -   id: script-runner
        args: ['./lint.sh']
        verbose: false
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.0.0
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-ast
    -   id: requirements-txt-fixer
